time:
  start: 1979-12-01
  end: 2013-01-01
  freq: 'M'

provinces:
  - 'Henan'
  - 'Neimeng'
  - 'Ningxia'
  - 'Qinghai'
  - 'Shandong'
  - 'Shanxi'
  - 'Shaanxi'
  - 'Gansu'

root: /Users/songshgeo/Documents/VSCode/ABSESpy

nature:
  crs: EPSG:4326

human:
  metric: payoff
  evolve_strategy: "best"
  # # ################# <0: reward; >0: punish
  s_enforcement_cost: 0.7  # Grid = 1 - S-enforcement-cost
  s_reputation: 0.60  # Group = S-reputation
  # voluntary_compliance_level: 0.00
  # rule_breaker_level: 0.03

  mutation_probability: 0.05
  # 连边的概率
  l_p: 1
  # metanorm: False
  # memory: False
  # reputation: False
  # memory_length: 1  # years
  # s_bad_reputation: 100
  # memory_reputation: 21
  # learn_strategy: 'best'
  # loss_coefficient: 0.7


hydro:
  Ks: 0.8

farmer:
  loss_coef: 0.8

city:
  quota_weighted_by: 'deficits'

city_id: 'City_ID'
crops_id:
  Rice: 12
  Wheat: 16
  Maize: 14

db:
  crops: data/water_quota/crops
  irr_data: data/water_quota/irr_lands.csv
  cities: zip://data/water_quota/YR_cities.zip
  population: data/water_quota/yr_pop_downscaled.tif
  et0: data/water_quota/FAO56_PM_pet0.nc
  prec: data/water_quota/prec_montly_01deg.nc
  wui: data/water_quota/wui.csv
  quota_after: data/water_quota/monthly_quotas_after2000.csv
  quota_before: data/water_quota/expecting_quotas_before2000.csv
