time:
  start: 1979-12-01
  end: 2013-01-01
  freq: 'M'

root: /Users/songshgeo/Documents/VSCode/ABSESpy

nature:
  crs: EPSG:4326


city_id: 'City_ID'
crops_id:
  Rice: 12
  Wheat: 16
  Maize: 14

db:
  irr_data: data/water_quota/irr_lands.csv
  cities: zip://data/water_quota/YR_cities.zip
  population: data/water_quota/yr_pop_downscaled.tif
